AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for our CICD PR'

Parameters:
  Environment:
    Type: String
    Deafault: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS:StackName}-${Enivronment}-bucket'
    Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Environment
        Value: GithubActionsTesting

  OutPuts:
    BucketName:
      Description: 'NAme of created S3 Bucket'
      Value: !Ref MyS3Bucket